### ISSUE TITLE
Please makce the plugin multilingual

### ISSUE THREAD

**Issue by pcav** [marcelgaucho/AdaplinTool#1]
So more users will be able to understand what is the plugin about.
Thanks.

**Comment by pcav** [comment]
sorry, invalid description. I understand your target may be Brazilian/Portuguese users, but the preferred approach would be to build the plugin as multilingual, with source in English, and adding translations (first obviously in PT_BR). It requires a little bit of extra work, which I'm sure will pay well off allowing more people to contribute and improve it.
Thanks for understanding.

**Comment by marcelgaucho** [comment]
Hello Paolo, I understand the importance of the english language also be present. But after the description in Portuguese, I've added the English description. Now I've added a line to separate the two descriptions and switched the order of presentation to be more clear . 
The source is already in English, with English comments.
Unfortunately I don't have the knowledge to build the translation part of the plugin, so I've changed the plugin to English language.

**Comment by marcelgaucho** [comment]
I've uploaded a new zip version of the plugin to QGIS repository with these changes.

**Comment by pcav** [comment]
Thanks for your reply. I heartily suggest you to ask in mailing list. Giving multilingual is quite easy, and opens up beautiful opportunities.

**Comment by marcelgaucho** [comment]
Thanks for the hint of asking in the mailing list, I will try to learn how to make the plugin multilingual.
